parameters:
  - name: EnvironmentName
    displayName: Azure Pipelines environment for k8s
    type: string
  - name: ResName
    displayName: Resource name in k8s environment
    type: string
  - name: ImageRepository
    displayName: Docker Image Respository
    type: string
  - name: K8sNamespace
    displayName: Kubernetes Namespace
    type: string
  - name: ServiceConnection
    displayName: Name of Docker Registry Service Connection
    type: string
  - name: ManifestPath
    displayName: Path to k8s app manifest
    type: string

stages:
  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    jobs:
      - deployment: Deploy
        displayName: Deploy job
        environment: "${{parameters.EnvironmentName}}.${{parameters.ResName}}"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@0
                  displayName: Deploy to Kubernetes cluster
                  inputs:
                    action: deploy
                    namespace: "${{parameters.K8sNamespace}}"
                    manifests: |
                      ${{parameters.ManifestPath}}
                    containers: |
                      ${{parameters.ServiceConnection}}/${{parameters.ImageRepository}}:latest
