parameters:
  - name: EnvironmentName
    displayName: Azure Pipelines environment for k8s
    type: string
  - name: ImageRepository
    displayName: Docker Image Respository
    type: string
  - name: K8sNamespace
    displayName: Kubernetes Namespace
    type: string
  - name: ServiceConnection
    displayName: Name of Docker Registry Service Connection
    type: string

stages:
  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    jobs:
      - deployment: Deploy
        displayName: Deploy job
        environment: "${{parameters.EnvironmentName}}"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    artifactName: "manifests"
                    downloadPath: "$(System.ArtifactsDirectory)/manifests"

                - task: KubernetesManifest@0
                  displayName: Deploy to Kubernetes cluster
                  inputs:
                    action: deploy
                    namespace: "${{parameters.K8sNamespace}}"
                    manifests: |
                      $(System.ArtifactsDirectory)/manifests/deployment.yml
                      $(System.ArtifactsDirectory)/manifests/service.yml
                    containers: |
                      ${{parameters.ServiceConnection}}/${{parameters.ImageRepository}}:$(Build.BuildId)
