parameters:
  - name: dblogin
    displayName: Login for Azure SQL server
    type: string
  - name: dbpasswd
    displayName: Password for Azure SQL server
    type: string
  - name: WorkDir
    displayName: Working Directory
    type: string

stages:
  - stage: Provision
    jobs:
      - job: InitApply
        steps:
          - script: |
              terraform init \
              && terraform apply -auto-approve \
              -var 'sql_login=${{parameters.dblogin}}' -var 'sql_password=${{parameters.dbpasswd}}'
            workingDirectory: "${{parameters.WorkDir}}"
            displayName: Terraform
            env:
              DB_LOGIN: $(DbLogin)
              DB_PASSWD: $(DbPasswd)
