parameters:
  - name: WorkDir
    displayName: Working Directory
    type: string

stages:
  - stage: Provision
    jobs:
      - job: InitApply
        steps:
          - script: |
              terraform init \
              && terraform apply -auto-approve -var 'sql_login=$(DB_LOGIN)' -var 'sql_password=$(DB_PASSWD)'
            workingDirectory: "${{parameters.WorkDir}}"
            displayName: Terraform
            env:
              DB_LOGIN: $(DbLogin)
              DB_PASSWD: $(DbPasswd)
