parameters:
  - name: WorkDir
    displayName: Working Directory
    type: string

stages:
  - stage: Provision
    jobs:
      - job: InitApply
        steps:
          - script: |
              terraform init \
              && terraform apply -auto-approve -var 'sql_login=$(DbLogin)' -var 'sql_password=$(DbPasswd)'
            workingDirectory: "${{parameters.WorkDir}}"
            displayName: Terraform
