parameters:
  - name: WorkDir
    displayName: Working Directory
    type: string
  - name: ConnString
    displayName: Database connection string
    type: string

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - script: |
              sed -i "s/Server=.*/${{parameters.ConnString}}\"/" appsettings.json
              dotnet tool install -g dotnet-ef
              export PATH="$PATH:$HOME/.dotnet/tools" >> ~/.bashrc
              source ~/.bashrc
              dotnet ef migrations add InitialCreate
              dotnet ef database update
            displayName: Perform database migrations
            workingDirectory: "${{parameters.WorkDir}}/DotNetCoreSqlDb"

          - task: DotNetCoreCLI@2
            displayName: "dotnet build"
            inputs:
              command: "build"
              solution: "*.sln"
              workingDirectory: "${{parameters.WorkDir}}"

          - task: DotNetCoreCLI@2
            inputs:
              command: publish
              publishWebProjects: True
              arguments: "--output $(Build.ArtifactStagingDirectory)"
              zipAfterPublish: True

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)"
              artifact: "drop"
              publishLocation: "pipeline"
