parameters:
  - name: ConnectionName
    displayName: AzureRM Service Connection Name
    type: string
  - name: AppName
    displayName: Azure Web App Name
    type: string
  - name: ResourceGroup
    displayName: Name of resource group of Azure Web App
    type: string

stages:
  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: "current"
              artifactName: "drop"
              targetPath: "$(System.ArtifactsDirectory)"

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: "AzureRM"
              azureSubscription: "${{parameters.ConnectionName}}"
              appType: "webApp"
              WebAppName: "${{parameters.AppName}}"
              packageForLinux: "$(Build.ArtifactStagingDirectory)/**/*.zip"

          - script: |
              az login --service-principal \
              -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
            displayName: az login

          - script: |
              az webapp config connection-string set \
              -g ${{parameters.ResourceGroup}} -n ${{parameters.AppName}} -t sqlazure \
              --settings MyDbConnection='$(DB_STRING)' > /dev/null
            displayName: Add SQL connection string
            env:
              DB_STRING: $(ConnString)
