trigger:
  - master

pool: My-AKS-Pool

variables:
  - group: VarGroup

stages:
  - template: pipeline-templates/00-provision.yaml
    parameters:
      workdir: dotnet-pipeline/infrastructure
  - template: pipeline-templates/01-build.yaml
    parameters:
      workdir: dotnet-pipeline/app
  - template: pipeline-templates/02-deploy.yaml
    parameters:
      ConnectionName: AzureConnection
      AppName: laslopaul-dotnetapp
      ResourceGroup: dotnetapp
