trigger:
  - master

pool: Default

stages:
  - template: pipeline-templates/00-provision.yaml
    parameters:
      workdir: docker-pipeline
  - template: pipeline-templates/01-build.yaml
    parameters:
      ImageRepository: laslopaul/dockerjsapp
      DockerfilePath: docker-pipeline/app/Dockerfile
      ServiceConnection: DockerHub
  - template: pipeline-templates/02-deploy.yaml
    parameters:
      EnvironmentName: aksnamespace
      ResName: default
      ImageRepository: laslopaul/dockerjsapp
      K8sNamespace: default
      ManifestPath: docker-pipeline/app.yaml
      ServiceConnection: DockerHub
